---
kind: pipeline
name: default-image-push-pull

concurrency:
  limit: 1

platform:
  os: linux
  arch: amd64

steps:
  - name: validate-list
    image: library/ubuntu:22.04
    commands:
    - grep -vE '^\s*(#|//)' images-list | sort -Vc
    - grep -vE '^\s*(#|//)' images-list-daily | sort -Vc
  - name: check-new-images-exist
    image: rancher/dapper:v0.6.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper check-new-images-exist.sh
    settings:
      custom_dns: 1.1.1.1
    when:
      event:
        - pull_request

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
